# Flask config
TESTING = True
SECRET_KEY = "secret"
PERMANENT_SESSION_LIFETIME = 3600
JSONIFY_PRETTYPRINT_REGULAR = True

# SQLAlchemy config
SQLALCHEMY_DATABASE_URI = "sqlite:///test.db"
SQLALCHEMY_TRACK_MODIFICATIONS = False
